### ISSUE TITLE
enable 2fa for rubygem owners

### ISSUE THREAD

**Issue by michaelglass** [NoRedInk/rails_edge_test#20]
Howdy

after https://github.com/rest-client/rest-client/issues/713, I think it's wise for all rubygem owners here to [enable 2fa on their rubygem accounts](https://guides.rubygems.org/setting-up-multifactor-authentication/). 

- [x] @jleven 
- [x] @ento 
- [x] @Arkham 
- [x] @michaelglass 
- [x] @mavnn 
- [x] @avh4

**Comment by rubyFeedback** [comment]
I've read through https://guides.rubygems.org/setting-up-multifactor-authentication/ and there are some issues with it. 

For example:

> Please use your authenticator to scan the QR code. 

I do not have that. I also do not know how to enable it.

It appears to push mandatory work onto the DEVELOPERS. This, thus, may punish all of them with additional work - people who never had anything compromised on rubygems.org, for example.

I am against an approach that penalizes everyone into usability concerns that may not be applicable or applied by them.

I have been using rubygems.org since 6 years or so fine, never had any issue that I was aware with with any of my gems. So why would I have to be penalized for something that I can not do? Note that I do not own a smartphone either, by the way. 

I am all up for improving the infrastructure but I am TOTALLY against this forced approach to penalize every single developer at rubygems.org.

**Comment by michaelglass** [comment]
@rubyFeedback do you mind removing your comment?
